tutorialsIndex_en = {"Basic", "Intermediate", "Advanced", "Professions", "Farming - Seeds", "Recipes - Doctor", "Recipes - Cooker", "Manual - Constructor"}

tutorialsInfo_en = {
    {
        {name = "01. Introduction", text = "Icon 1: Is the Battle Window (where they will find creatures and players around).\n\Icon 2: Is the Combat Control.\n\Icon 3: Is the information of life and energy.\n\Icon 4: Represents your inventory.\n\Icon 5: Is the map.\n\Icon 6: Is your browsing window.\n\Icon 7: It is their Skills.\n\Icon 8: Is your list of friends.\n\Icon 9: Is a list of your achievements.\n\Icon 10: Is their spells and attacks.", img = "imgs/b1"}, 
        {name = "02. Handling Items", text = "To handle items, just click and hold the left mouse button and drag it to where you want, you can move items into or out of their inventory, and also collect them or throw them away.\n\nHowever there are only items that can not be discarded.", img = "imgs/b2"}, 
        {name = "03. Attacking enemies", text = "To attack an enemy, just click your target (right mouse button), then the target is checked, you will attack the enemy automatically.", img = "imgs/b3"}, 
        {name = "04. Using Attacks", text = "Their attacks are unlocked as you level rises. To use an attack just click its icon (left mouse button), or use the shortcuts 'F1, F2, F3, F4, ...'. Shortcuts can also be redefined in the Hotkeys settings.", img = "imgs/b4"}, 
        {name = "05. Creatures Loot", text = "Toda criatura depois de derrotado pode conter itens, para coletá-los, apenas clique na criatura caida (botão direito do mouse).", img = "imgs/b5"}, 
        {name = "06. Restoring health/energy", text = "To recover your life, just eating some kind of food, which can be dropped on creatures. Another way is to use life potion (as shown).\n\To use potions, click the right button on it and then click the left upon you or player who wants to use the potion. Another way is using Hotkeys.", img = "imgs/b6"}, 
        {name = "07. Map", text = "The game map can be opened with the shortcut 'Ctrl + F' or its icon.\n\nThe map shows important locations such as cities and shops.\n\nTo view the map in its entirety, use 'Ctrl + Shift + M'.", img = "imgs/b7"}, 
		{name = "08. Store", text = "To open the inventory of a store, incie a conversation with you and tell npc:\n\n-Hi.\n\n-Trade.", img = "imgs/b8"}, 
        {name = "09. Deposit", text = "The deposit can be found in any center of deposits to open, just click on the deposit (right mouse button). In the warehouse you can store as many items as you want.", img = "imgs/b9"}
    },
    {
        {name = "01. Look items", text = "To look something, place your mouse and press the two buttons simultaneously.\n\nAnother way to looking at something is by using 'Ctrl' + right mouse button and selecting the 'look'.\n\nLook is very useful to get information about items, mainly to learn their names.", img = "imgs/i1"},
        {name = "02. Combate controls", text = "Combat controls are very important, especially for hunting.\n\nOffensive: Attack extra, but rather the defense is lost.\n\nBalanced: Balanced Force\n\nDefensive: extra defense but rather lost attack.\n\nFollow attack: This option allows you to automatically follow the creature that you are attacking.\n\nEnable PvP: Enabling this option you will be able to attack other people, but PvP is only allowed after Level 10.", img = "imgs/i2"},
        {name = "03. Hotkeys", text = "Here you can add new shortcuts and to put items such as potions, or battle commands as attacks etc.", img = "imgs/i3"},
        {name = "04. Accepting Quests", text = "To accept basic quests is very simple, start the conversation with the NPC with the word 'hi', then offer help to the NPC to 'help', then accept the quest with 'yes'.\n\nWhen complete the requested task, return to NPC and repeat the same process.\n\nMore complex quests require their own interpretation to discover involved dialogue.", img = "imgs/i4"},
        {name = "05. Friend list", text = "The friends list shows whether your friends are Online or Offline in the game, and provides various options like private messages or ignore.\n\nTo add a friend is very easy, just click the right button in the list, select the option to add and enter the name of the player you want to add.\n\nAnother way to add someone, is holding 'Ctrl' and clicking on the player you want to add, then select the option.", img = "imgs/i5"},
    },	
    {
        {name = "01. Trade", text = "To make an exchange, hold 'Ctrl' and click the right mouse button on the item you want to change and select 'Trade with', then use the player you want to make the switch. (in case of multiple items, place them in a bag and change the bag).", img = "imgs/a1"},
        {name = "02. Cut tree", text = "To cut a tree, use the right-click in your axe, then with the left mouse button, click on the trees for cutting (similar or equal to the above image).", img = "imgs/a2"},
        {name = "03. Mining", text = "To mine a rock, use the right-click in your pickaxe, then with the left mouse button click on the rocks to mining (similar or equal to the above image).", img = "imgs/a3"},
        {name = "04. Farming", text = "To plant something, talk to NPC Donald and buy the seed you want (remembering that the greater your level of farming, more options you will have to plant). To plow the earth click on the right mouse button on the hoe, and then the left mouse button over the own soil for planting, after click on the right mouse button on the seed and use the left click on the ground that you plowed.\n\To see how much time is left to collect your planting, tell to Donald:\n\Hi.\n\List.\n\To collect your planting, tell to Donald:\n\Hi.\n\Collect.", img = "imgs/a4"},
        {name = "05. Make Kaen Stone", text = "To make Kaen Stone drag Kaen boshi upon Small Stone or vice versa.\n\\n\Items necessary: Kaen Boshi, Small Stone.\n\Level necessary: 15.\n\Observation 1: You can do Kaen Stones as you want at once, since the number of Kaen Boshis and Small Stones are equal.\n\Observation 2: It must be Usopp to do.", img = "imgs/a5"},
        {name = "06. Make Kemuri Stone", text = "To make Kemuri Stone drag Kemuri boshi upon Small Stone or vice versa.\n\\n\Items necessary: Kemuri Boshi, Small Stone.\n\Level necessary: 20.\n\Observation 1: You can do Kemuri Stones as you want at once, since the number of Kemuri Boshis and Small Stones are equal.\n\Observation 2: It must be Usopp to do.", img = "imgs/a6"},
        {name = "07. Make Pop Stone", text = "To make Pop Stone, Pop Green drag on the Small Stone or vice versa.\n\\n\Items necessary: Pop Green, Small Stone.\n\Level necessary: 30.\n\Observation 1: You can do Pop Stones as you want at once, since the number of Pop Greens and Small Stones are equal.\n\Observation 2: It must be Usopp to do.", img = "imgs/a7"},
        {name = "08. Fishing", text = "To fish, just click the right mouse button on the fishing rod (which should be in your hand) and use in any lake or sea (bottom left), remembering that you must have bait (worms for example) in your bag or waist to fish. When a fish takes the bait (water moves around the bait), click on the bait right again.\n\nNew fish appear depending on your level of fishing.\n\nTip: Baits can be bought at NPC Fiherman.", img = "imgs/a8"},
        {name = "09. Houses", text = "To buy a house, you need to have VIP account and at least level 30.\n\First find a house without an owner, 'look at' the front door to check and know the price, then stand facing the front door and enter! Buyhouse.\n\Every month will be charged the price of the house of your deposit, otherwise you will lose your home (the items are shipped to the warehouse automatically). To view information on the rental type !houseinfo.\n\The home owner has several commands:\n\!invite - To invite someone to your home.\n\!subowner - To set a second owner for the house.\n\!door - To define who can open certain door (stand facing the door in question).\n\!kick player - To throw the person out of their home.\n\!sellhouse player - To sell the house for any player.\n\!leavehouse - To leave the house.", img = "imgs/a9"},
        {name = "10. Party e Channels", text = "1. Private Chat Channel - To create a private channel and invite players\n2. Game-Chat - Channel for talks.\n3. Trade - Channel trade, buy and sell items.\n4. Help - Channel helps to questions tutors.", img = "imgs/a10"},
    },	
    {
        {name = "01. Choosing profession", text = "To choose your profession, go to the NPC of your chosen profession and tell:\n\n-Hi.\n\n-Help.\n\n-Yes.", img = "imgs/p1"},
        {name = "02. Constructor",           text = "To train professional constructor, go to the NPC Constructor Tutor and tell:\n\n-Hi.\n\n-Enter.\n\n-Yes.\n\n- Open Table construction by clicking the right mouse button on it or by pressing Ctrl + right button and then choosing the option open, place the material you want to make the specific item you want, you might need one in your backpack Toolkit , then click again right on the table, and then click Work.\n\nObs: The constructor's instructions will be in the guide, Manual – Constructor.", img = "imgs/p2"},
        {name = "03. Doctor",               text = "To train professional doctor, go to the NPC Doctor and tell:\n\n-Hi.\n\n-Enter.\n\n-Yes.\n\n- Open the bottle of potions by clicking the right mouse button on it or by pressing Ctrl + right button and then choosing the option open, put the ingredient you want to make the specific item you want, then click again right on the bottle and then click Work.\n\nObs: The doctor's instructions will be in the guide, Recipes – Doctor.", img = "imgs/p3"},
        {name = "04. Cooker",           text = "To train professional cooker, go to the NPC Cooking Tutor and tell:\n\n-Hi.\n\n-Enter.\n\n-Yes.\n\n- Open the stove click on the right mouse button on it or by pressing Ctrl + right button and then choosing the option open, put the ingredient you want to make the recipe specifies that you want, then click again right on the stove and then click Work.\n\nObs: The cooker's instructions will be in the guide, Recipes – Cooker.", img = "imgs/p4"},
    },	
    {
        {name = "01. Cherry", text = "Premium: No.\n\Level: 3.\n\Fatigue: 2.\n\Skill: 1.\n\Exp: 0.\n\Amount: 4.\n\Time: 11min.", img = "imgs/f1"},
        {name = "02. Bulb of Garlic", text = "Premium: No.\n\Level: 5.\n\Fatigue: 3.\n\Skill: 2.\n\Exp: 0.\n\Quantidade: 4.\n\Time: 13min.", img = "imgs/f2"}, 
        {name = "04. irita", text = "Premium: No.\n\Level: 5.\n\Fatigue: 3.\n\Skill: 2.\n\Exp: 0.\n\Amount: 2.\n\Time: 13min.", img = "imgs/f3"},
        {name = "05. Onion", text = "Premium: No.\n\Level: 8.\n\Fatigue: 3.\n\Skill: 3.\n\Exp: 0.\n\Amount: 3.\n\Time: 18min.", img = "imgs/f4"},
        {name = "06. Tomato", text = "Premium: No.\n\Level: 8.\n\Fatigue: 3.\n\Skill: 3.\n\Exp: 0.\n\Amount: 5.\n\Time: 18min.", img = "imgs/f5"},
        {name = "07. jalapeno Pepper", text = "Premium: No.\n\Level: 10.\n\Fatigue: 5.\n\Skill: 5.\n\Exp: 0.\n\Quantidade: 4.\n\Time: 22min.", img = "imgs/f6"},
        {name = "08. Green Guam", text = "Premium: No.\n\Level: 10.\n\Fatigue: 5.\n\Skill: 5.\n\Exp: 0.\n\Amount: 2.\n\Time: 21min.", img = "imgs/f7"},
        {name = "09. Red Guam", text = "Premium: No.\n\Level: 10.\n\Fatigue: 5.\n\Skill: 5.\n\Exp: 0.\n\Amount: 2.\n\Time: 21min.", img = "imgs/f8"},
        {name = "10. Carrot", text = "Premium: No.\n\Level: 12.\n\Fatigue: 6.\n\Skill: 7.\n\Exp: 0.\n\Amount: 4.\n\Time: 25min.", img = "imgs/f9"},
        {name = "11. Potato", text = "Premium: No.\n\Level: 13.\n\Fatigue: 7.\n\Skill: 8.\n\Exp: 0.\n\Amount: 3.\n\Time: 27min.", img = "imgs/f10"},
        {name = "12. Rannar", text = "Premium: No.\n\Level: 13.\n\Fatigue: 7.\n\Skill: 8.\n\Exp: 0.\n\Amount: 3.\n\Time: 25min.", img = "imgs/f11"},
        {name = "13. Pear", text = "Premium: No.\n\Level: 15.\n\Fatigue: 8.\n\Skill: 10.\n\Exp: 0.\n\Amount: 5.\n\Time: 31min.", img = "imgs/f12"},
        {name = "14. Lettuce", text = "Premium: No.\n\Level: 15.\n\Fatigue: 8.\n\Skill: 10.\n\Exp: 0.\n\Amount: 5.\n\Time: 31min.", img = "imgs/f13"},
        {name = "15. Wergali", text = "Premium: Yes.\n\Level: 15.\n\Fatigue: 8.\n\Skill: 11.\n\Exp: 0.\n\Amount: 3.\n\Time: 27min.", img = "imgs/f14"},
        {name = "15. Orange", text = "Premium: Yes.\n\Level: 17.\n\Fatigue: 9.\n\Skill: 13.\n\Exp: 0.\n\Amount: 5.\n\Time: 42min.", img = "imgs/f15"},
        {name = "15. Plum", text = "Premium: Yes.\n\Level: 17.\n\Fatigue: 9.\n\Skill: 13.\n\Exp: 0.\n\Amount: 4.\n\Time: 42min.", img = "imgs/f16"},
        {name = "15. Peas", text = "Premium: Yes.\n\Level: 18.\n\Fatigue: 10.\n\Skill: 15.\n\Exp: 0.\n\Amount: 5.\n\Time: 45min.", img = "imgs/f17"},
        {name = "15. Mango", text = "Premium: Yes.\n\Level: 19.\n\Fatigue: 10.\n\Skill: 16.\n\Exp: 0.\n\Amount: 4.\n\Time: 46min.", img = "imgs/f18"},
        {name = "15. Banana", text = "Premium: Yes.\n\Level: 20.\n\Fatigue: 11.\n\Skill: 18.\n\Exp: 0.\n\Amount: 5.\n\Time: 48min.", img = "imgs/f19"},
        {name = "15. Beet", text = "Premium: Yes.\n\Level: 20.\n\Fatigue: 11.\n\Skill: 18.\n\Exp: 0.\n\Amount: 5.\n\Time: 48min.", img = "imgs/f20"},
        {name = "15. Broccoli", text = "Premium: Yes.\n\Level: 20.\n\Fatigue: 12.\n\Skill: 20.\n\Exp: 0.\n\Amount: 5.\n\Time: 53min.", img = "imgs/f21"},
        {name = "15. Raspberry", text = "Premium: Yes.\n\Level: 20.\n\Fatigue: 12.\n\Skill: 20.\n\Exp: 0.\n\Amount: 5.\n\Time: 53min.", img = "imgs/f22"},
        {name = "15. Grapes", text = "Premium: Yes.\n\Level: 21.\n\Fatigue: 15.\n\Skill: 21.\n\Exp: 0.\n\Amount: 6.\n\Time: 55min.", img = "imgs/f23"},
        {name = "15. Lemon", text = "Premium: Yes.\n\Level: 21.\n\Fatigue: 15.\n\Skill: 22.\n\Exp: 0.\n\Amount: 6.\n\Time: 56min.", img = "imgs/f24"},
        {name = "15. Green Tarromin", text = "Premium: Yes.\n\Level: 22.\n\Fatigue: 16.\n\Skill: 23.\n\Exp: 0.\n\Amount: 2.\n\Time: 57min.", img = "imgs/f25"},
        {name = "15. Red Tarromin", text = "Premium: Yes.\n\Level: 22.\n\Fatigue: 16.\n\Skill: 23.\n\Exp: 0.\n\Amount: 2.\n\Time: 57min.", img = "imgs/f26"},
        {name = "15. Coconut", text = "Premium: Yes.\n\Level: 22.\n\Fatigue: 17.\n\Skill: 24.\n\Exp: 0.\n\Amount: 8.\n\Time: 58min.", img = "imgs/f27"},
        {name = "15. Cucumber", text = "Premium: Yes.\n\Level: 23.\n\Fatigue: 18.\n\Skill: 25.\n\Exp: 0.\n\Amount: 7.\n\Time: 60min.", img = "imgs/f28"},
        {name = "15. Aubergine", text = "Premium: Yes.\n\Level: 23.\n\Fatigue: 18.\n\Skill: 25.\n\Exp: 0.\n\Amount: 7.\n\Time: 60min.", img = "imgs/f29"},
        {name = "15. Cauliflower", text = "Premium: Yes.\n\Level: 24.\n\Fatigue: 20.\n\Skill: 27.\n\Exp: 0.\n\Amount: 6.\n\Time: 62min", img = "imgs/f30"},
        {name = "15. Melon", text = "Premium: Yes.\n\Level: 24.\n\Fatigue: 21.\n\Skill: 0.\n\Exp: 28.\n\Amount: 5.\n\Time: 63min.", img = "imgs/f31"},
        {name = "15. Pumpkin", text = "Premium: Yes.\n\Level: 25.\n\Fatigue: 22.\n\Skill: 0.\n\Exp: 30.\n\Amount: 5.\n\Time: 65min.", img = "imgs/f32"},
        {name = "15. Corncob", text = "Premium: Yes.\n\Level: 25.\n\Fatigue: 22.\n\Skill: 0.\n\Exp: 30.\n\Amount: 7.\n\Time: 65min.", img = "imgs/f33"},
        {name = "15. Pineapple", text = "Premium: Yes.\n\Level: 35.\n\Fatigue: 24.\n\Skill: 0.\n\Exp: 35.\n\Amount: 5.\n\Time: 70min.", img = "imgs/f34"},
        {name = "15. Green Harralander", text = "Premium: Yes.\n\Level: 30.\n\Fatigue: 29.\n\Skill: 40.\n\Exp: 0.\n\Amount: 2.\n\Time: 85min.", img = "imgs/f35"},
        {name = "15. Red Harralander", text = "Premium: Yes.\n\Level: 30.\n\Fatigue: 29.\n\Skill: 40.\n\Exp: 0.\n\Amount: 2.\n\Time: 85min.", img = "imgs/f36"},    
    },
    {
        {name = "01. Health Potion", text = "Skill: 1.\n\Level: 3.\n\Exp: 9.\n\Fatigue: 2.\n\Level to use: 1.\n\Voc: All.\n\Heal: 125-175Hp.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/m1"},
        {name = "02. Energy Potion", text = "Skill: 1.\n\Level: 3.\n\Exp: 9.\n\Fatigue: 2.\n\Level to use: 1.\n\Voc: All.\n\Heal: 75-125En.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/m2"},
        {name = "03. Poison Antidote", text = "Skill: 5.\n\Level: 5.\n\Exp: 10.\n\Fatigue: 3.\n\Level to use: 1.\n\Voc: All.\n\Heal: 0.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/m3"}, 
        {name = "04. Health-time Potion", text = "Skill: 10.\n\Level: 5.\n\Exp: 15.\n\Fatigue: 4.\n\Level to use: 15.\n\Voc: All.\n\Heal: 190Hp(10hp/s).\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/m4"},
        {name = "05. Energy-time Potion", text = "Skill: 10.\n\Level: 5.\n\Exp: 15.\n\Fatigue: 4.\n\Level to use: 15.\n\Voc: All.\n\Heal: 140En(10en/s).\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/m5"},
        {name = "06. Fire Antidote", text = "Skill: 10.\n\Level: 5.\n\Exp: 11.\n\Fatigue: 3.\n\Level to use: 1.\n\Voc: All.\n\Heal: 0.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/m6"},
        {name = "07. Eletric Antidote", text = "Skill: 15.\n\Level: 5.\n\Exp: 12.\n\Fatigue: 3.\n\Level to use: 1.\n\Voc: All.\n\Heal: 0.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/m7"},
        {name = "08. Mixed Antidote", text = "Skill: 25.\n\Level: 10.\n\Exp: 37.\n\Fatigue: 9.\n\Level to use: 1.\n\Voc: All.\n\Heal: 0.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/m8"},
        {name = "09. Strong Health Potion", text = "Skill: 30.\n\Level: 15.\n\Exp: 45.\n\Fatigue: 10.\n\Level to use: 50.\n\Voc: Sanji, Luffy, Zoro, Ace, Usopp.\n\Heal: 250-350Hp.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/m9"},
        {name = "10. Strong Energy Potion", text = "Skill: 30.\n\Level: 15.\n\Exp: 45.\n\Fatigue: 10.\n\Level to use: 50.\n\Voc: Ace, Usopp, Nami, Chopper.\n\Heal: 115-185En.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/m10"},
        {name = "11. Strong Health-time Potion", text = "Skill: 35.\n\Level: 20.\n\Exp: 58.\n\Fatigue: 14.\n\Level to use: 60.\n\Voc: Sanji, Luffy, Zoro, Ace, Usopp.\n\Heal: 375Hp(15hp/s).\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/m11"},
        {name = "12. Strong Energy-time Potion", text = "Skill: 35.\n\Level: 20.\n\Exp: 58.\n\Fatigue: 14.\n\Level to use: 60.\n\Voc: Ace, Usopp, Nami, Chopper.\n\Heal: 210En(15en/s).\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/m12"},
        {name = "13. Great Mixed Potion", text = "Skill: 50.\n\Level: 25.\n\Exp: 92.\n\Fatigue: 21.\n\Level to use: 80.\n\Voc: Ace, Usopp.\n\Heal: 250-350Hp/115-185En.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/m13"},
        {name = "14. Great Health Potion", text = "Skill: 50.\n\Level: 25.\n\Exp: 105.\n\Fatigue: 23.\n\Level to use: 80.\n\Voc: Sanji, Luffy, Zoro.\n\Heal: 425-575Hp.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/m14"},
        {name = "15. Great Energy Potion", text = "Skill: 50.\n\Level: 25.\n\Exp: 105.\n\Fatigue: 23.\n\Level to use: 80.\n\Voc: Nami, Chopper.\n\Heal: 150-250En.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/m15"},   
    },		
    {
        {name = "01. Sweet Bread", text = "Skill: 1.\n\Level: 3.\n\Exp: 9.\n\Fatigue: 2.\n\Duração: 6min.\n\Voc: All.\n\Premium to do: No.\n\Premium to eat: No.\n\Buff: Normal Regen.\n\Cotegory: Feed.", img = "imgs/c1"},
        {name = "02. Cherry Drink",           text = "Skill: 2.\n\Level: 3.\n\Exp: 9.\n\Fatigue: 3.\n\Duração: 7min.\n\Voc: All.\n\Premium to do: No.\n\Premium to eat: No.\n\Buff: Normal Regen.\n\Cotegory: Feed.", img = "imgs/c2"},
        {name = "03. Grilled Sardines",           text = "Skill: 3.\n\Level: 3.\n\Exp: 11.\n\Fatigue: 3.\n\Duração: 3min.\n\Voc: Sanji, Luffy, Zoro, Ace, Usopp, Chopper.\n\Premium to do: No.\n\Premium to eat: No.\n\Buff: +5% Damage.\n\Cotegory: Skill.", img = "imgs/c3"},    
        {name = "04. Barbecue",           text = "Skill: 4.\n\Level: 3.\n\Exp: 12.\n\Fatigue: 3.\n\Duração: 3min.\n\Voc: All.\n\Premium to do: No.\n\Premium to eat: No.\n\Buff: +5% Defense.\n\Cotegory: Skill.", img = "imgs/c4"},
        {name = "05. Chicken Sandwich",           text = "Skill: 5.\n\Level: 5.\n\Exp: 15.\n\Fatigue: 4.\n\Duração: 8min.\n\Voc: All.\n\Premium to do: No.\n\Premium to eat: No.\n\Buff: Normal Regen + 5 Speed.\n\Cotegory: Speed.", img = "imgs/c5"},
        {name = "06. Pudding",           text = "Skill: 5.\n\Level: 5.\n\Exp: 15.\n\Fatigue: 4.\n\Duração: 6min.\n\Voc: Sanji, Luffy, Zoro, Ace, Usopp, Chopper.\n\Premium to do: No.\n\Premium to eat: No.\n\Buff: Normal Regen + 5 Critical.\n\Cotegory: Skill.", img = "imgs/c6"},
        {name = "07. Cake",           text = "Skill: 7.\n\Level: 5.\n\Exp: 18.\n\Fatigue: 5.\n\Duração: 6min 30sec.\n\Voc: Ace, Nami, Chopper.\n\Premium to do: No.\n\Premium to eat: No.\n\Buff: Normal Regen + 1 ML.\n\Cotegory: Skill.", img = "imgs/c7"},
        {name = "08. Roast Chicken",           text = "Skill: 9.\n\Level: 10.\n\Exp: 9.\n\Fatigue: 6.\n\Duração: 4min.\n\Voc: All.\n\Premium to do: No.\n\Premium to eat: Yes.\n\Buff: Regen 1.5x.\n\Cotegory: Skill.", img = "imgs/c8"},
        {name = "09. Porridge",           text = "Skill: 10.\n\Level: 5.\n\Exp: 21.\n\Fatigue: 7.\n\Duração: 6min.\n\Voc: Sanji, Luffy, Zoro, Ace, Usopp, Chopper.\n\Premium to do: No.\n\Premium to eat: Yes.\n\Buff: +2 Strenght, Meele Weapon, Distance.\n\Cotegory: Skill.", img = "imgs/c9"},
        {name = "10. Chocolate Cake",           text = "Skill: 12.\n\Level: 5.\n\Exp: 24.\n\Fatigue: 7.\n\Duração: 6min.\n\Voc: All.\n\Premium to do: No.\n\Premium to eat: Yes.\n\Buff: +2 Defense.\n\Cotegory: Skill.", img = "imgs/c10"},
        {name = "11. Fishburguer",           text = "Skill: 13.\n\Level: 5.\n\Exp: 26.\n\Fatigue: 8.\n\Duração: 10min.\n\Voc: All.\n\Premium to do: No.\n\Premium to eat: Yes.\n\Buff: Normal Regen.\n\Cotegory: Feed.", img = "imgs/c11"},
        {name = "12. Cherrycake", text = "Skill: 15.\n\Level: 10.\n\Exp: 30.\n\Fatigue: 8.\n\Duração: 3min.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: +10% Damage.\n\Cotegory: Skill.", img = "imgs/c12"},
        {name = "13. Meatloaf", text = "Skill: 17.\n\Level: 10.\n\Exp: 32.\n\Fatigue: 9.\n\Duração: 3min.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: +10 Defense.\n\Cotegory: Skill.", img = "imgs/c13"},
        {name = "14. Carrot Cake", text = "Skill: 20.\n\Level: 10.\n\Exp: 37.\n\Fatigue: 10.\n\Duração: 3min.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: Regen 1.5x + 10 Speed.\n\Cotegory: Heal, Speed.", img = "imgs/c14"},
        {name = "15. Tuna Salad", text = "Skill: 20.\n\Level: 10.\n\Exp: 37.\n\Fatigue: 10.\n\Duração: 3min.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: Regen 1.5x + 6 Critical.\n\Cotegory: Heal, Skill.", img = "imgs/c15"},
        {name = "16. Meat Stew", text = "Skill: 23.\n\Level: 15.\n\Exp: 52.\n\Fatigue: 13.\n\Duração: 3min.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: +15% Fast Attack.\n\Cotegory: Skill.", img = "imgs/c16"},
        {name = "17. Taco", text = "Skill: 25.\n\Level: 20.\n\Exp: 42.\n\Fatigue: 12.\n\Duração: 10min.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: Normal Regen + 25 speed.\n\Cotegory: Feed, Speed.", img = "imgs/c17"},
        {name = "18. Fruit Cocktail", text = "Skill: 27.\n\Level: 20.\n\Exp: 45.\n\Fatigue: 13.\n\Duração: 10min.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: 115 Speed.\n\Cotegory: Speed.", img = "imgs/c18"},
        {name = "19. Sushi", text = "Skill: 30.\n\Level: 20.\n\Exp: 50.\n\Fatigue: 13.\n\Duração: 4min.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: Regen 2x.\n\Cotegory: Heal.", img = "imgs/c19"},
        {name = "20. Pasta", text = "Skill: 33.\n\Level: 20.\n\Exp: 55.\n\Fatigue: 14.\n\Duração: 1min.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: +15% Strenght, Meele Weapon, Distance.\n\Cotegory: Skill.", img = "imgs/c20"},
        {name = "21. Juice of Vegetables", text = "Skill: 36.\n\Level: 20.\n\Exp: 60.\n\Fatigue: 15.\n\Duração: 1min.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: +3 Energy Level.\n\Cotegory: Skill.", img = "imgs/c21"},
        {name = "22. Steak and eggs", text = "Skill: 40.\n\Level: 25.\n\Exp: 68.\n\Fatigue: 15.\n\Duração: 6min.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: Regen 1.5x.\n\Cotegory: Heal.", img = "imgs/c22"},
        {name = "23. Salad", text = "Skill: 44.\n\Level: 25.\n\Exp: 77.\n\Fatigue: 17.\n\Duração: 2min 30sec.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: +15% Health Max, Normal Regen.\n\Cotegory: Skill, Feed.", img = "imgs/c23"},
        {name = "24. Shredded Lobster", text = "Skill: 46.\n\Level: 25.\n\Exp: 92.\n\Fatigue: 17.\n\Duração: 2min 30sec.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: +15% Mana Max, Normal Regen.\n\Cotegory: Skill, Feed.", img = "imgs/c24"},
        {name = "25. Roast Pacu", text = "Skill: 50.\n\Level: 25.\n\Exp: 98.\n\Fatigue: 18.\n\Duração: 5min.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: +15% Fast Attack, +6 Critical.\n\Cotegory: Skill.", img = "imgs/c25"},
        {name = "26. Breaded Fillet", text = "Skill: 55.\n\Level: 25.\n\Exp: 110.\n\Fatigue: 20.\n\Duração: 3min 30sec.\n\Voc: All.\n\Premium to do: Yes.\n\Premium to eat: Yes.\n\Buff: +10% Damage, +10% Defense.\n\Cotegory: Skill.", img = "imgs/c26"},
            },	
    {
        {name = "01. Small stone", text = "Skill: 1.\n\Level: 3.\n\Exp: 5.\n\Fatigue: 1.\n\Necessary: Toolkit.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/t1"},
        {name = "02. Cedar Plank",           text = "Skill: 1.\n\Level: 3.\n\Exp: 5.\n\Fatigue: 1.\n\Necessary: Toolkit.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/t2"},
        {name = "03. Hoe",           text = "Skill: 2.\n\Level: 3.\n\Exp: 8.\n\Fatigue: 2.\n\Necessary: Toolkit.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/t3"},
        {name = "04. Light Shovel", text = "Skill: 3.\n\Level: 3.\n\Exp: 10.\n\Fatigue: 2.\n\Necessary: Toolkit.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/t4"},   
        {name = "05. Fishing Rod", text = "Skill: 5.\n\Level: 5.\n\Exp: 14.\n\Fatigue: 5.\n\Necessary: Toolkit.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/t5"}, 
        {name = "06. Stone Axe", text = "Skill: 5.\n\Level: 5.\n\Exp: 14.\n\Fatigue: 5.\n\Necessary: Toolkit.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/t6"}, 
        {name = "07. Stone Pickaxe", text = "Skill: 5.\n\Level: 5.\n\Exp: 14.\n\Fatigue: 5.\n\Necessary: Toolkit.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/t37"},
        {name = "08. Iron Bar", text = "Skill: 5.\n\Level: 5.\n\Exp: 30.\n\Fatigue: 5.\n\Necessary: Toolkit.\n\Premium to do: No.\n\Premium to use: Yes.", img = "imgs/t8"},
        {name = "09. Wooden Chair", text = "Skill: 6.\n\Level: 5.\n\Exp: 16.\n\Fatigue: 3.\n\Necessary: Toolkit.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/t9"},
        {name = "10. Square Table", text = "Skill: 7.\n\Level: 5.\n\Exp: 17.\n\Fatigue: 3.\n\Necessary: Toolkit.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/t10"},
        {name = "11. Drawers", text = "Skill: 8.\n\Level: 5.\n\Exp: 18.\n\Fatigue: 3.\n\Necessary: Toolkit.\n\Premium to do: No.\n\Premium to use: No.", img = "imgs/t11"},
        {name = "12. Cedar Boat I", text = "Skill: 10.\n\Level: 10.\n\Exp: 180.\n\Fatigue: 100.\n\Necessary: Toolkit.\n\Premium to do: No.\n\Premium to use: Yes.", img = "imgs/t12"},
        {name = "13. Oak Plank", text = "Skill: 12.\n\Level: 10.\n\Exp: 8.\n\Fatigue: 2.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t13"},
        {name = "14. Improved Fishing Rod", text = "Skill: 13.\n\Level: 10.\n\Exp: 28.\n\Fatigue: 10.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t14"},
        {name = "15. Iron Axe", text = "Skill: 13.\n\Level: 10.\n\Exp: 33.\n\Fatigue: 10.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t15"},
        {name = "16. Iron Pickaxe", text = "Skill: 13.\n\Level: 10.\n\Exp: 33.\n\Fatigue: 10.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t16"},
        {name = "17. Bronze Bar", text = "Skill: 15.\n\Level: 15.\n\Exp: 55.\n\Fatigue: 10.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: Yes.", img = "imgs/t17"},
        {name = "18. Iron Bullet Device", text = "Skill: 15.\n\Level: 15.\n\Exp: 80.\n\Fatigue: 40.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t18"},
        {name = "19. Time table", text = "Skill: 17.\n\Level: 15.\n\Exp: 36.\n\Fatigue: 10.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t19"},
        {name = "20. Tree Stump", text = "Skill: 18.\n\Level: 15.\n\Exp: 36.\n\Fatigue: 10.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t20"},
        {name = "21. Box", text = "Skill: 20.\n\Level: 15.\n\Exp: 39.\n\Fatigue: 10.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t21"},
        {name = "22. Big Table", text = "Skill: 22.\n\Level: 15.\n\Exp: 40.\n\Fatigue: 10.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t22"},
        {name = "23. Oak Boat I", text = "Skill: 25.\n\Level: 20.\n\Exp: 340.\n\Fatigue: 200.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: Yes.", img = "imgs/t23"},  
        {name = "24. Copper Bullet Device", text = "Skill: 30.\n\Level: 20.\n\Exp: 150.\n\Fatigue: 80.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t24"},  
        {name = "25. Cage", text = "Skill: 33.\n\Level: 20.\n\Exp: 95.\n\Fatigue: 30.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t25"},  
        {name = "26. Bronze Axe", text = "Skill: 33.\n\Level: 20.\n\Exp: 155.\n\Fatigue: 30.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t26"},  
        {name = "27. Bronze Pickaxe", text = "Skill: 33.\n\Level: 20.\n\Exp: 155.\n\Fatigue: 30.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t27"},  
        {name = "28. White Horse Toy", text = "Skill: 35.\n\Level: 20.\n\Exp: 40.\n\Fatigue: 10.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t28"},  
        {name = "29. Brown Horse Toy", text = "Skill: 35.\n\Level: 20.\n\Exp: 40.\n\Fatigue: 10.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t29"},  
        {name = "30. Painted Horse Toy", text = "Skill: 35.\n\Level: 20.\n\Exp: 40.\n\Fatigue: 10.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t30"},  
        {name = "31. Teak Plank", text = "Skill: 37.\n\Level: 20.\n\Exp: 13.\n\Fatigue: 3.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t31"},
        {name = "32. Silver Bar", text = "Skill: 40.\n\Level: 25.\n\Exp: 90.\n\Fatigue: 20.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t32"},
        {name = "33. Teak Boat I", text = "Skill: 40.\n\Level: 25.\n\Exp: 700.\n\Fatigue: 300.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: Yes.", img = "imgs/t33"},
        {name = "34. Large Trunk", text = "Skill: 42.\n\Level: 25.\n\Exp: 75.\n\Fatigue: 15.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t34"},
        {name = "35. Spinning Rod", text = "Skill: 45.\n\Level: 25.\n\Exp: 190.\n\Fatigue: 50.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t35"},
        {name = "36. Steel Axe", text = "Skill: 45.\n\Level: 25.\n\Exp: 270.\n\Fatigue: 50.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t36"},
        {name = "37. Steel Pickaxe", text = "Skill: 45.\n\Level: 25.\n\Exp: 270.\n\Fatigue: 50.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t7"},
        {name = "38. Silver Bullet Device", text = "Skill: 48.\n\Level: 25.\n\Exp: 275.\n\Fatigue: 120.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t42"},
        {name = "39. Wooden Drawer", text = "Skill: 49.\n\Level: 25.\n\Exp: 90.\n\Fatigue: 15.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t39"},
        {name = "40. Wooden Cabinet", text = "Skill: 50.\n\Level: 25.\n\Exp: 150.\n\Fatigue: 18.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t40"},
        {name = "41. Wooden Wardrob", text = "Skill: 51.\n\Level: 25.\n\Exp: 155.\n\Fatigue: 18.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: No.", img = "imgs/t41"},
        {name = "42. Special Bullet Device", text = "Skill: 55.\n\Level: 25.\n\Exp: 250.\n\Fatigue: 250.\n\Necessary: Toolkit.\n\Premium to do: Yes.\n\Premium to use: Yes.", img = "imgs/t38"}, 
          
    },	    
}